Repository ShaunakSensarma/GolangEcommerce, pull requests merged in 2023-06, with the labels that each got.

#1 Correcting readme file
  README.md
Labels: documentation

#2 Adding file structure, incoming routes and data model
  README.md
  controllers/address.go
  controllers/cart.go
  controllers/controllers.go
  database/cart.go
  database/databasetup.go
  docker-compose.yml
  go.mod
  main.go
  middleware/middleware.go
  models/models.go
  routes/routes.go
  tokens/tokengen.go
Labels: enhancement

#5 Create codeql.yml
  .github/workflows/codeql.yml
Labels: ci-check

#6 Create dependency-review.yml
  .github/workflows/dependency-review.yml
Labels: ci-check

#9 Create super-linter.yml
  .github/workflows/super-linter.yml
Labels: ci-check
